// <auto-generated />
namespace Store.Domain.DataContexts.DomainMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class brand : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(brand));
        
        string IMigrationMetadata.Id
        {
            get { return "201401011824029_brand"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
