// <auto-generated />
namespace codesnippets.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class language : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(language));
        
        string IMigrationMetadata.Id
        {
            get { return "201505282245173_language"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
